import type {
  Robot,
  JobOffering,
  Job,
  Settlement,
  AgentWallet,
  FleetPolicy,
  EarningsDataPoint,
} from "./types";

// ─── Robots ──────────────────────────────────────────────────────────

export const ROBOTS: Robot[] = [
  {
    id: "r1",
    name: "G1-ALPHA",
    model: "Unitree G1",
    owner: "0x742d...3F1a",
    wallet: "0x8a3F...c2d1",
    status: "active",
    reputation: 4.9,
    stake: 500,
    capabilities: ["CARRY", "NAVIGATE"],
    battery: 87,
    jobsCompleted: 142,
    jobsFailed: 2,
    earningsTotal: 248.5,
    earningsToday: 22.5,
    currentJobId: "JOB-0x7F3A",
    location: "Zone B · Transit",
  },
  {
    id: "r2",
    name: "G1-BETA",
    model: "Unitree G1",
    owner: "0x742d...3F1a",
    wallet: "0x1b4E...a8f2",
    status: "idle",
    reputation: 4.7,
    stake: 400,
    capabilities: ["CARRY", "NAVIGATE", "SORT"],
    battery: 92,
    jobsCompleted: 98,
    jobsFailed: 3,
    earningsTotal: 171.25,
    earningsToday: 14.0,
    currentJobId: null,
    location: "Charging Station",
  },
  {
    id: "r3",
    name: "G1-DELTA",
    model: "Unitree G1",
    owner: "0x742d...3F1a",
    wallet: "0x3c7A...d4e5",
    status: "active",
    reputation: 4.8,
    stake: 450,
    capabilities: ["CARRY", "INSPECT"],
    battery: 64,
    jobsCompleted: 115,
    jobsFailed: 1,
    earningsTotal: 201.75,
    earningsToday: 18.25,
    currentJobId: "JOB-0x2B1C",
    location: "Zone A · Row 2",
  },
  {
    id: "r4",
    name: "G1-GAMMA",
    model: "Unitree G1",
    owner: "0x742d...3F1a",
    wallet: "0x5d9B...f6a7",
    status: "charging",
    reputation: 4.6,
    stake: 350,
    capabilities: ["NAVIGATE", "INSPECT", "SORT"],
    battery: 23,
    jobsCompleted: 76,
    jobsFailed: 4,
    earningsTotal: 132.0,
    earningsToday: 8.75,
    currentJobId: null,
    location: "Charging Station",
  },
  {
    id: "r5",
    name: "G1-EPSILON",
    model: "Unitree G1",
    owner: "0x742d...3F1a",
    wallet: "0x7e1C...b8d9",
    status: "maintenance",
    reputation: 4.5,
    stake: 300,
    capabilities: ["CARRY"],
    battery: 100,
    jobsCompleted: 54,
    jobsFailed: 5,
    earningsTotal: 94.5,
    earningsToday: 0,
    currentJobId: null,
    location: "Maintenance Bay",
  },
  {
    id: "r6",
    name: "G1-ZETA",
    model: "Unitree G1",
    owner: "0x742d...3F1a",
    wallet: "0x9f2D...c0e1",
    status: "idle",
    reputation: 4.85,
    stake: 475,
    capabilities: ["CARRY", "NAVIGATE", "INSPECT", "SORT"],
    battery: 78,
    jobsCompleted: 128,
    jobsFailed: 1,
    earningsTotal: 224.0,
    earningsToday: 16.5,
    currentJobId: null,
    location: "Zone C · Row 1",
  },
];

// ─── Job Offerings ───────────────────────────────────────────────────

export const JOB_OFFERINGS: JobOffering[] = [
  {
    id: "off-1",
    robotId: "r1",
    robotName: "G1-ALPHA",
    robotModel: "Unitree G1",
    robotReputation: 4.9,
    robotStake: 500,
    robotJobsCompleted: 142,
    taskType: "CARRY",
    priceUsdc: 1.75,
    slaMinutes: 5,
    etaMinutes: 2,
    active: true,
  },
  {
    id: "off-2",
    robotId: "r1",
    robotName: "G1-ALPHA",
    robotModel: "Unitree G1",
    robotReputation: 4.9,
    robotStake: 500,
    robotJobsCompleted: 142,
    taskType: "NAVIGATE",
    priceUsdc: 1.2,
    slaMinutes: 8,
    etaMinutes: 3,
    active: true,
  },
  {
    id: "off-3",
    robotId: "r2",
    robotName: "G1-BETA",
    robotModel: "Unitree G1",
    robotReputation: 4.7,
    robotStake: 400,
    robotJobsCompleted: 98,
    taskType: "CARRY",
    priceUsdc: 1.9,
    slaMinutes: 5,
    etaMinutes: 3,
    active: true,
  },
  {
    id: "off-4",
    robotId: "r2",
    robotName: "G1-BETA",
    robotModel: "Unitree G1",
    robotReputation: 4.7,
    robotStake: 400,
    robotJobsCompleted: 98,
    taskType: "SORT",
    priceUsdc: 2.5,
    slaMinutes: 10,
    etaMinutes: 5,
    active: true,
  },
  {
    id: "off-5",
    robotId: "r3",
    robotName: "G1-DELTA",
    robotModel: "Unitree G1",
    robotReputation: 4.8,
    robotStake: 450,
    robotJobsCompleted: 115,
    taskType: "CARRY",
    priceUsdc: 1.8,
    slaMinutes: 5,
    etaMinutes: 2.5,
    active: true,
  },
  {
    id: "off-6",
    robotId: "r3",
    robotName: "G1-DELTA",
    robotModel: "Unitree G1",
    robotReputation: 4.8,
    robotStake: 450,
    robotJobsCompleted: 115,
    taskType: "INSPECT",
    priceUsdc: 2.0,
    slaMinutes: 8,
    etaMinutes: 4,
    active: true,
  },
  {
    id: "off-7",
    robotId: "r6",
    robotName: "G1-ZETA",
    robotModel: "Unitree G1",
    robotReputation: 4.85,
    robotStake: 475,
    robotJobsCompleted: 128,
    taskType: "CARRY",
    priceUsdc: 1.85,
    slaMinutes: 5,
    etaMinutes: 2,
    active: true,
  },
  {
    id: "off-8",
    robotId: "r6",
    robotName: "G1-ZETA",
    robotModel: "Unitree G1",
    robotReputation: 4.85,
    robotStake: 475,
    robotJobsCompleted: 128,
    taskType: "NAVIGATE",
    priceUsdc: 1.15,
    slaMinutes: 8,
    etaMinutes: 3,
    active: true,
  },
  {
    id: "off-9",
    robotId: "r6",
    robotName: "G1-ZETA",
    robotModel: "Unitree G1",
    robotReputation: 4.85,
    robotStake: 475,
    robotJobsCompleted: 128,
    taskType: "INSPECT",
    priceUsdc: 1.95,
    slaMinutes: 8,
    etaMinutes: 4,
    active: true,
  },
  {
    id: "off-10",
    robotId: "r4",
    robotName: "G1-GAMMA",
    robotModel: "Unitree G1",
    robotReputation: 4.6,
    robotStake: 350,
    robotJobsCompleted: 76,
    taskType: "SORT",
    priceUsdc: 2.3,
    slaMinutes: 10,
    etaMinutes: 5,
    active: false,
  },
];

// ─── Jobs ────────────────────────────────────────────────────────────

export const JOBS: Job[] = [
  {
    id: "JOB-0x7F3A",
    client: "MERCHANT-7",
    clientAddress: "0xaB3c...7F3a",
    robotId: "r1",
    robotName: "G1-ALPHA",
    taskType: "CARRY",
    from: "Rack B3",
    to: "Dispatch Bay 2",
    fromCoords: [52.412, -1.509],
    toCoords: [52.413, -1.508],
    bounty: 2.0,
    bid: 1.75,
    slaMinutes: 5,
    status: "executing",
    phase: "navigating_delivery",
    createdAt: "2026-03-08T03:12:00Z",
    completedAt: null,
    timeElapsedMinutes: 2.1,
    proofGps: null,
    proofTimestamp: null,
    proofSensorHash: null,
    schema: "ROVA-CARRY-v1",
    txHash: "0x3f8a...c2d1",
  },
  {
    id: "JOB-0x2B1C",
    client: "LOGISTICS-3",
    clientAddress: "0xdE5f...2B1c",
    robotId: "r3",
    robotName: "G1-DELTA",
    taskType: "INSPECT",
    from: "Rack A2",
    to: "Inspection Point",
    fromCoords: [52.411, -1.51],
    toCoords: [52.414, -1.507],
    bounty: 2.5,
    bid: 2.0,
    slaMinutes: 8,
    status: "executing",
    phase: "picking_up",
    createdAt: "2026-03-08T03:14:00Z",
    completedAt: null,
    timeElapsedMinutes: 1.5,
    proofGps: null,
    proofTimestamp: null,
    proofSensorHash: null,
    schema: "ROVA-INSPECT-v1",
    txHash: "0x9e2b...f4a7",
  },
  {
    id: "JOB-0x5D4E",
    client: "MERCHANT-7",
    clientAddress: "0xaB3c...7F3a",
    robotId: "r1",
    robotName: "G1-ALPHA",
    taskType: "CARRY",
    from: "Rack A1",
    to: "Dispatch Bay 1",
    fromCoords: [52.41, -1.511],
    toCoords: [52.413, -1.509],
    bounty: 1.8,
    bid: 1.6,
    slaMinutes: 5,
    status: "completed",
    phase: "settled",
    createdAt: "2026-03-08T02:48:00Z",
    completedAt: "2026-03-08T02:51:22Z",
    timeElapsedMinutes: 3.37,
    proofGps: [52.413, -1.509],
    proofTimestamp: "2026-03-08T02:51:18Z",
    proofSensorHash: "0x4d1f...e8c3",
    schema: "ROVA-CARRY-v1",
    txHash: "0x7c3e...a1b2",
  },
  {
    id: "JOB-0x8A2F",
    client: "WAREHOUSE-AI",
    clientAddress: "0xfA7b...8A2f",
    robotId: "r2",
    robotName: "G1-BETA",
    taskType: "SORT",
    from: "Rack C1",
    to: "Rack A3",
    fromCoords: [52.415, -1.512],
    toCoords: [52.41, -1.509],
    bounty: 3.0,
    bid: 2.5,
    slaMinutes: 10,
    status: "completed",
    phase: "settled",
    createdAt: "2026-03-08T02:30:00Z",
    completedAt: "2026-03-08T02:38:45Z",
    timeElapsedMinutes: 8.75,
    proofGps: [52.41, -1.509],
    proofTimestamp: "2026-03-08T02:38:40Z",
    proofSensorHash: "0xa9c2...b3d4",
    schema: "ROVA-SORT-v1",
    txHash: "0x5e8f...c1d2",
  },
  {
    id: "JOB-0x1C3D",
    client: "MERCHANT-7",
    clientAddress: "0xaB3c...7F3a",
    robotId: "r6",
    robotName: "G1-ZETA",
    taskType: "NAVIGATE",
    from: "Charging Station",
    to: "Rack B2",
    fromCoords: [52.409, -1.513],
    toCoords: [52.412, -1.51],
    bounty: 1.5,
    bid: 1.15,
    slaMinutes: 8,
    status: "completed",
    phase: "settled",
    createdAt: "2026-03-08T02:15:00Z",
    completedAt: "2026-03-08T02:20:14Z",
    timeElapsedMinutes: 5.23,
    proofGps: [52.412, -1.51],
    proofTimestamp: "2026-03-08T02:20:10Z",
    proofSensorHash: "0xb4e7...d5f6",
    schema: "ROVA-NAVIGATE-v1",
    txHash: "0x8d3a...e2f3",
  },
  {
    id: "JOB-0x6E5F",
    client: "LOGISTICS-3",
    clientAddress: "0xdE5f...2B1c",
    robotId: "r3",
    robotName: "G1-DELTA",
    taskType: "CARRY",
    from: "Rack B1",
    to: "Dispatch Bay 3",
    fromCoords: [52.412, -1.511],
    toCoords: [52.414, -1.508],
    bounty: 2.2,
    bid: 1.8,
    slaMinutes: 5,
    status: "completed",
    phase: "settled",
    createdAt: "2026-03-08T01:55:00Z",
    completedAt: "2026-03-08T01:58:33Z",
    timeElapsedMinutes: 3.55,
    proofGps: [52.414, -1.508],
    proofTimestamp: "2026-03-08T01:58:30Z",
    proofSensorHash: "0xc5f8...e6a7",
    schema: "ROVA-CARRY-v1",
    txHash: "0x2a4b...f3g4",
  },
  {
    id: "JOB-0x9G7H",
    client: "MERCHANT-7",
    clientAddress: "0xaB3c...7F3a",
    robotId: "r5",
    robotName: "G1-EPSILON",
    taskType: "CARRY",
    from: "Rack C2",
    to: "Dispatch Bay 1",
    fromCoords: [52.415, -1.511],
    toCoords: [52.413, -1.509],
    bounty: 1.9,
    bid: 1.7,
    slaMinutes: 5,
    status: "failed",
    phase: "settled",
    createdAt: "2026-03-08T01:30:00Z",
    completedAt: "2026-03-08T01:36:12Z",
    timeElapsedMinutes: 6.2,
    proofGps: [52.414, -1.51],
    proofTimestamp: "2026-03-08T01:36:08Z",
    proofSensorHash: "0xd6a9...f7b8",
    schema: "ROVA-CARRY-v1",
    txHash: "0x3b5c...g4h5",
  },
  {
    id: "JOB-0x4F8G",
    client: "WAREHOUSE-AI",
    clientAddress: "0xfA7b...8A2f",
    robotId: null,
    robotName: null,
    taskType: "INSPECT",
    from: "Rack A1",
    to: "Inspection Point",
    fromCoords: [52.41, -1.511],
    toCoords: [52.414, -1.507],
    bounty: 2.8,
    bid: null,
    slaMinutes: 8,
    status: "open",
    phase: "posted",
    createdAt: "2026-03-08T03:16:00Z",
    completedAt: null,
    timeElapsedMinutes: null,
    proofGps: null,
    proofTimestamp: null,
    proofSensorHash: null,
    schema: "ROVA-INSPECT-v1",
    txHash: null,
  },
  {
    id: "JOB-0xA1B2",
    client: "LOGISTICS-3",
    clientAddress: "0xdE5f...2B1c",
    robotId: null,
    robotName: null,
    taskType: "CARRY",
    from: "Rack B2",
    to: "Dispatch Bay 1",
    fromCoords: [52.412, -1.51],
    toCoords: [52.413, -1.509],
    bounty: 2.1,
    bid: null,
    slaMinutes: 5,
    status: "open",
    phase: "posted",
    createdAt: "2026-03-08T03:17:00Z",
    completedAt: null,
    timeElapsedMinutes: null,
    proofGps: null,
    proofTimestamp: null,
    proofSensorHash: null,
    schema: "ROVA-CARRY-v1",
    txHash: null,
  },
  {
    id: "JOB-0xC3D4",
    client: "MERCHANT-7",
    clientAddress: "0xaB3c...7F3a",
    robotId: null,
    robotName: null,
    taskType: "NAVIGATE",
    from: "Charging Station",
    to: "Rack C1",
    fromCoords: [52.409, -1.513],
    toCoords: [52.415, -1.512],
    bounty: 1.4,
    bid: null,
    slaMinutes: 8,
    status: "open",
    phase: "posted",
    createdAt: "2026-03-08T03:18:00Z",
    completedAt: null,
    timeElapsedMinutes: null,
    proofGps: null,
    proofTimestamp: null,
    proofSensorHash: null,
    schema: "ROVA-NAVIGATE-v1",
    txHash: null,
  },
];

// ─── Settlements ─────────────────────────────────────────────────────

export const SETTLEMENTS: Settlement[] = [
  {
    id: "stl-1",
    jobId: "JOB-0x5D4E",
    client: "MERCHANT-7",
    provider: "G1-ALPHA",
    robotPayment: 1.5952,
    protocolFee: 0.0048,
    refund: 0.2,
    taskType: "CARRY",
    timestamp: "2026-03-08T02:51:22Z",
    txHash: "0x7c3e...a1b2",
    chain: "Base Sepolia",
  },
  {
    id: "stl-2",
    jobId: "JOB-0x8A2F",
    client: "WAREHOUSE-AI",
    provider: "G1-BETA",
    robotPayment: 2.4925,
    protocolFee: 0.0075,
    refund: 0.5,
    taskType: "SORT",
    timestamp: "2026-03-08T02:38:45Z",
    txHash: "0x5e8f...c1d2",
    chain: "Base Sepolia",
  },
  {
    id: "stl-3",
    jobId: "JOB-0x1C3D",
    client: "MERCHANT-7",
    provider: "G1-ZETA",
    robotPayment: 1.1466,
    protocolFee: 0.0034,
    refund: 0.35,
    taskType: "NAVIGATE",
    timestamp: "2026-03-08T02:20:14Z",
    txHash: "0x8d3a...e2f3",
    chain: "Base Sepolia",
  },
  {
    id: "stl-4",
    jobId: "JOB-0x6E5F",
    client: "LOGISTICS-3",
    provider: "G1-DELTA",
    robotPayment: 1.7946,
    protocolFee: 0.0054,
    refund: 0.4,
    taskType: "CARRY",
    timestamp: "2026-03-08T01:58:33Z",
    txHash: "0x2a4b...f3g4",
    chain: "Base Sepolia",
  },
  {
    id: "stl-5",
    jobId: "JOB-0x9G7H",
    client: "MERCHANT-7",
    provider: "G1-EPSILON",
    robotPayment: 0,
    protocolFee: 0,
    refund: 1.9,
    taskType: "CARRY",
    timestamp: "2026-03-08T01:36:12Z",
    txHash: "0x3b5c...g4h5",
    chain: "Base Sepolia",
  },
  {
    id: "stl-6",
    jobId: "JOB-0xPREV1",
    client: "LOGISTICS-3",
    provider: "G1-ALPHA",
    robotPayment: 1.3965,
    protocolFee: 0.0035,
    refund: 0.1,
    taskType: "CARRY",
    timestamp: "2026-03-08T01:12:00Z",
    txHash: "0x6f7g...h8i9",
    chain: "Base Sepolia",
  },
  {
    id: "stl-7",
    jobId: "JOB-0xPREV2",
    client: "MERCHANT-7",
    provider: "G1-ZETA",
    robotPayment: 1.945,
    protocolFee: 0.005,
    refund: 0.05,
    taskType: "INSPECT",
    timestamp: "2026-03-08T00:48:00Z",
    txHash: "0x9h0i...j1k2",
    chain: "Base Sepolia",
  },
];

// ─── Agent Wallet ────────────────────────────────────────────────────

export const AGENT_WALLET: AgentWallet = {
  address: "0xaB3c...7F3a",
  name: "MERCHANT-7",
  balance: 847.25,
  totalSpent: 152.75,
  activeEscrow: 3.75,
  jobsPosted: 47,
};

// ─── Fleet Policy ────────────────────────────────────────────────────

export const FLEET_POLICY: FleetPolicy = {
  acceptedTaskTypes: ["CARRY", "NAVIGATE", "INSPECT", "SORT"],
  priceFloors: { CARRY: 1.5, NAVIGATE: 1.0, INSPECT: 1.5, SORT: 2.0 },
  priceCeilings: { CARRY: 5.0, NAVIGATE: 4.0, INSPECT: 6.0, SORT: 8.0 },
  maxConcurrentJobs: 3,
  geofenceEnabled: true,
  geofenceBounds: { lat: [52.408, 52.416], lng: [-1.514, -1.506] },
  autoAccept: false,
  maxDailyWithdraw: 100,
  emergencyPaused: false,
};

// ─── Earnings Chart Data ─────────────────────────────────────────────

export const EARNINGS_24H: EarningsDataPoint[] = [
  { hour: "04:00", amount: 0 },
  { hour: "05:00", amount: 0 },
  { hour: "06:00", amount: 1.2 },
  { hour: "07:00", amount: 3.5 },
  { hour: "08:00", amount: 5.8 },
  { hour: "09:00", amount: 8.2 },
  { hour: "10:00", amount: 7.1 },
  { hour: "11:00", amount: 9.4 },
  { hour: "12:00", amount: 11.2 },
  { hour: "13:00", amount: 8.8 },
  { hour: "14:00", amount: 6.5 },
  { hour: "15:00", amount: 10.1 },
  { hour: "16:00", amount: 12.3 },
  { hour: "17:00", amount: 14.7 },
  { hour: "18:00", amount: 11.9 },
  { hour: "19:00", amount: 9.2 },
  { hour: "20:00", amount: 7.6 },
  { hour: "21:00", amount: 5.3 },
  { hour: "22:00", amount: 3.8 },
  { hour: "23:00", amount: 2.1 },
  { hour: "00:00", amount: 1.4 },
  { hour: "01:00", amount: 4.2 },
  { hour: "02:00", amount: 6.8 },
  { hour: "03:00", amount: 3.5 },
];

// ─── Incoming Jobs for Robot View ────────────────────────────────────

export const INCOMING_JOBS_FOR_ROBOT: Job[] = JOBS.filter(
  (j) => j.status === "open"
);

// ─── Helper: Get robot by ID ─────────────────────────────────────────

export function getRobotById(id: string): Robot | undefined {
  return ROBOTS.find((r) => r.id === id);
}

export function getJobById(id: string): Job | undefined {
  return JOBS.find((j) => j.id === id);
}
